name: Sphinx build

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install sphinx sphinx_rtd_theme sphinxcontrib-napoleon
    - name: Build Docs
      run: sphinx-apidoc -f -o docs/source ./src/niftitorch/
    - name: Build HTML
      run: sphinx-build -b html docs/source docs/build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/
        publish_branch: gh-pages